services:
  - type: web
    name: super_quiz_backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - package.json
        - server.js
        - "**/*.js"
